#!/usr/bin/python3.2
# -*- coding: utf-8 -*-

dicionario = {
                'abaular':  'a|ba|u|lar',
                'acuidade': 'a|cui|da|de',
                'água': 'á|gua',
                'águas': 'á|guas',
                'ajuizado': 'a|ju|i|za|do',
                'ajuizar': 'a|ju|i|zar',
                'ambíguo': 'am|bí|guo',
                'ao': 'ao',
                'aos': 'aos',
                'arruinado': 'ar|ru|i|na|do',
                'arruinar': 'ar|ru|i|nar',
                'biunívoco': 'bi|u|ní|vo|co',
                'borda-d\'água': 'bor|da|dá|gu|a',
                'caimento': 'ca|i|men|to',
                'caíque': 'ca|í|que',
                'ciumento': 'ci|u|men|to',
                'cocainómano': 'co|ca|i|nó|ma|no',
                'coibir': 'co|i|bir',
                'conspicuidade': 'cons|pi|cui|da|de',
                'copo-d\'água': 'co|po|dá|gu|a',
                'decaimento': 'de|ca|i|men|to',
                'deiscência': 'de|is|cên|ci|a',
                'desajuizado': 'de|sa|ju|i|za|do',
                'desajuizar': 'de|sa|ju|i|zar',
                'diurese': 'di|u|re|se',
                'diurético': 'di|u|ré|ti|co',
                'diuturnidade': 'di|u|tur|ni|da|de',
                'druida': 'dru|i|da',
                'einsteiniano': 'eins|tei|ni|a|no',
                'embaimento': 'em|ba|i|men|to',
                'enciumar': 'en|ci|u|mar',
                'enraizar': 'en|ra|i|zar',
                'ensanduichar': 'en|san|du|i|char',
                'enviuvar': 'en|vi|u|var',
                'esmiuçar': 'es|mi|u|çar',
                'faiscar': 'fa|is|car',
                'gaseificação': 'ga|sei|fi|ca|ção',
                'gaseificar': 'ga|sei|fi|car',
                'genuinamente': 'ge|nu|i|na|men|te',
                'gratuidade': 'gra|tui|da|de',
                'heroinomania': 'he|ro|i|no|ma|ni|a',
                'improficuidade': 'im|pro|fi|cui|da|de',
                'inocuidade': 'i|no|cui|da|de',
                'língua': 'lín|gua',
                'maoísmo': 'mao|ís|mo',
                'maometano': 'mao|me|ta|no',
                'míngua': 'mín|gua',
                'miudeza': 'mi|u|de|za',
                'miudezas': 'mi|u|de|zas',
                'oblíqua': 'ob|lí|qu|a',
                'obliquamente': 'ob|li|qua|men|te',
                'oblíquo': 'ob|lí|qu|o',
                'palavrado': 'pa|la|vra|do',
                'proibição': 'pro|i|bi|ção',
                'proibir': 'pro|i|bir',
                'proibitivamente': 'pro|i|bi|ti|va|men|te',
                'proibitivo': 'pro|i|bi|ti|vo',
                'pst': 'pst',
                'retraimento': 're|tra|i|men|to',
                'reunião': 're|u|ni|ão',
                'reunificação': 're|u|ni|fi|ca|ção',
                'reunificar': 're|u|ni|fi|car',
                'reunir': 're|u|nir',
                'ruidosamente': 'ru|i|do|sa|men|te',
                'ruidoso': 'ru|i|do|so',
                'ruinosamente': 'ru|i|no|sa|men|te',
                'ruinoso': 'ru|i|no|so',
                'subalimentação': 'sub|a|li|men|ta|ção',
                'sublevação': 'sub|le|va|ção',
                'suicida': 'su|i|ci|da',
                'suicidar-se': 'su|i|ci|dar|se',
                'suicídio': 'su|i|cí|di|o',
                'suinicultor': 'su|i|ni|cul|tor',
                'suinicultura': 'su|i|ni|cul|tu|ra',
                'trava-língua': 'tra|va|lín|gua',
                'tréguas': 'tré|guas',
                'tromba-d\'água': 'trom|ba|dá|gu|a',
                'vacuidade': 'va|cui|da|de',
                'viuvez': 'vi|u|vez',
                'yeatsiano': 'ye|at|si|a|no'
}


def check(word):
    if word in dicionario:
        return dicionario[word]
    return False

if __name__ == "__main__":
    pass
